#!/usr/bin/env bash
set -euo pipefail

# 从 ai-ideas-bot 导入最新日报到博客，并清理超过 7 天的自动生成文章
# 用法：./scripts/import-ai-ideas.sh [保留天数]

KEEP_DAYS="${1:-7}"

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
REPORT_DIR="${ROOT_DIR}/../ai-ideas-bot/reports"
BLOG_DIR="${ROOT_DIR}/src/data/post"

if [[ ! -d "$REPORT_DIR" ]]; then
  echo "未找到日报目录: $REPORT_DIR"
  exit 1
fi

LATEST_REPORT="$(ls -1 "$REPORT_DIR"/*-ai-ideas.md 2>/dev/null | sort | tail -n 1 || true)"
if [[ -z "$LATEST_REPORT" ]]; then
  echo "未找到可导入的日报文件（*-ai-ideas.md）"
  exit 1
fi

BASENAME="$(basename "$LATEST_REPORT")"
REPORT_DATE="$(echo "$BASENAME" | sed -E 's/^([0-9]{4}-[0-9]{2}-[0-9]{2})-ai-ideas\.md$/\1/')"
if ! [[ "$REPORT_DATE" =~ ^[0-9]{4}-[0-9]{2}-[0-9]{2}$ ]]; then
  echo "无法从文件名解析日期: $BASENAME"
  exit 1
fi

PUB_DATE="${REPORT_DATE}"
TARGET_FILE="${BLOG_DIR}/${REPORT_DATE}-ai-ideas-auto.md"
TMP_FILE="${TARGET_FILE}.tmp"

# 构建博客文章（保留原日报内容）
cat > "$TMP_FILE" <<EOF
---
title: 'AI 点子日报 ${REPORT_DATE}'
excerpt: '自动导入 ai-ideas-bot 的当日机会日报。'
publishDate: ${PUB_DATE}
image: '~/assets/images/default.png'
category: 'AI'
tags: ['AI点子', '自动化', '日报']
source: 'ai-ideas-bot'
autoGenerated: true
---

> 本文由脚本自动导入，源文件：\`${BASENAME}\`

EOF

cat "$LATEST_REPORT" >> "$TMP_FILE"
mv "$TMP_FILE" "$TARGET_FILE"

echo "✅ 已导入: $TARGET_FILE"

# 清理超过 KEEP_DAYS 的自动导入文章（仅匹配 *-ai-ideas-auto.md）
NOW_TS="$(date +%s)"
for f in "$BLOG_DIR"/*-ai-ideas-auto.md; do
  [[ -e "$f" ]] || continue
  name="$(basename "$f")"
  file_date="$(echo "$name" | sed -E 's/^([0-9]{4}-[0-9]{2}-[0-9]{2})-ai-ideas-auto\.md$/\1/')"
  [[ "$file_date" =~ ^[0-9]{4}-[0-9]{2}-[0-9]{2}$ ]] || continue

  file_ts="$(date -d "$file_date" +%s 2>/dev/null || echo 0)"
  [[ "$file_ts" -eq 0 ]] && continue

  age_days=$(( (NOW_TS - file_ts) / 86400 ))
  if (( age_days > KEEP_DAYS )); then
    rm -f "$f"
    echo "🧹 已清理过期自动文章: $name（${age_days}天）"
  fi
done

echo "✅ 保留策略已执行：仅保留最近 ${KEEP_DAYS} 天自动导入文章"
